# Generated by Django 4.2.30 on 2026-08-06 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', '店長'), ('STAFF', '美甲師')], default='STAFF', max_length=10, verbose_name='角色權限')),
                ('provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='booking.provider', verbose_name='關聯的美甲師實體')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='booking.shop', verbose_name='所屬店家')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號')),
            ],
            options={
                'verbose_name': '工作人員權限檔',
                'verbose_name_plural': '工作人員權限檔',
            },
        ),
    ]
