# Generated by Django 4.2.30 on 2026-06-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='結束時間')),
                ('status', models.CharField(choices=[('PENDING', '待確認'), ('CONFIRMED', '已確認'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='預約狀態')),
                ('memo', models.TextField(blank=True, verbose_name='客戶備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='人員名稱')),
                ('is_manager', models.BooleanField(default=False, verbose_name='是否為店長')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店家名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='成品圖網址')),
                ('materials_note', models.TextField(blank=True, verbose_name='材料與色號紀錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='booking.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='實作時間(分鐘)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='價格')),
                ('providers', models.ManyToManyField(related_name='provided_services', to='booking.provider')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.shop')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='booking.shop'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手機號碼')),
                ('line_uid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINE UID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='booking.shop')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.provider'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.serviceitem'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.shop'),
        ),
    ]
