# Generated by Django 4.2.30 on 2026-07-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='addon_appointments', to='booking.serviceitem'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('HAND', '手部服務'), ('FOOT', '足部服務'), ('PURE_REMOVAL', '純卸甲'), ('ADDON', '加購項目')], default='HAND', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='is_addon',
            field=models.BooleanField(default=False, verbose_name='是否為加購項'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_appointments', to='booking.serviceitem'),
        ),
    ]
