# Generated by Django 4.2.30 on 2026-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_addons_serviceitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='price_type',
            field=models.CharField(choices=[('FIXED', '固定定價'), ('STARTING', '最低起價'), ('QUOTE', '現場溝通報價')], default='FIXED', max_length=10),
        ),
    ]
