# Generated by Django 4.2.30 on 2026-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_serviceitem_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='實際收費'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', '待確認'), ('CONFIRMED', '已確認'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='預約狀態'),
        ),
    ]
