# Generated by Django 4.2.30 on 2026-08-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_appointment_service_appointment_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BASE', '款式底價'), ('ADDON', '加價項目'), ('STYLE', '進階造型'), ('REMOVAL', '卸甲服務')], max_length=20, verbose_name='項目分類')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='預設單價')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顯示排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_price_items', to='booking.shop')),
            ],
            options={
                'verbose_name': '設計款價目項目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDesignQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='預收定金')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='優惠折扣')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='項目小計')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='應付尾款')),
                ('formatted_receipt', models.TextField(blank=True, verbose_name='格式化明細文字快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_quote', to='booking.appointment', verbose_name='關聯預約單')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDesignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BASE', '款式底價'), ('ADDON', '加價項目'), ('STYLE', '進階造型'), ('REMOVAL', '卸甲服務')], max_length=20, verbose_name='分類')),
                ('item_name', models.CharField(max_length=100, verbose_name='項目名稱快照')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價快照')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否為現場臨時新增項目')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.appointmentdesignquote')),
            ],
        ),
    ]
