# Generated by Django 4.2.30 on 2026-08-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_designpriceitem_appointmentdesignquote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='排班日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='上班時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='下班時間')),
                ('is_off', models.BooleanField(default=False, verbose_name='是否公休')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='booking.provider', verbose_name='美甲師')),
            ],
            options={
                'verbose_name': '美甲師班表',
                'verbose_name_plural': '美甲師班表',
                'indexes': [models.Index(fields=['provider', 'date'], name='booking_pro_provide_f0b97c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providershift',
            constraint=models.UniqueConstraint(fields=('provider', 'date'), name='unique_provider_date_shift'),
        ),
    ]
