# Generated by Django 4.2.30 on 2026-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_providershift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providershift',
            name='break_times',
            field=models.JSONField(blank=True, default=list, verbose_name='當日休息時段'),
        ),
    ]
