# Generated by Django 4.2.30 on 2026-08-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_providershift_break_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdesignquote',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='design_quotes', to='booking.shop', verbose_name='店家'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='booking.shop', verbose_name='店家'),
            preserve_default=False,
        ),
    ]
