# Generated by Django 4.2.30 on 2026-08-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
