# Generated by Django 4.2.30 on 2026-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('HAND', '手部美甲'), ('FOOT', '足部美甲'), ('PURE_REMOVAL', '純保養/純卸甲'), ('EAR', '采耳'), ('ADDON', '加購項目')], default='HAND', max_length=20),
        ),
    ]
